---
name: Clojure Snyk Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - snyk_test

jobs:
 snyk_scan:
   runs-on: ubuntu-latest
   steps:
    - uses: twingate/github-action@v1
      with:
        service-key: ${{ secrets.TWINGATE_PUBLIC_REPO_KEY }}
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@fix_name_mismatch
      with:
        snykToken: ${{ secrets.SNYK_TOKEN }}
        snykOrg: 'sectest'
        snykPolicy: '.snyk'
        snykProject: ${{ github.event.repository.name }}
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
